name: Deploy Snapshots

on:
  push:
    branches: ['master', '1.x']

  repository_dispatch:
    types: ['deploy-snapshots']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # Check out the code
      - uses: actions/checkout@v3

      # Enable caching of Maven dependencies to speed up job execution
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Set up Java 8 with Maven including a .m2/settings.xml file
      - name: Set up JDK 8 and Maven settings file
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Or 'zulu' if needed
          java-version: '8.0.442+6'  # Exact available version
          server-id: openmrs-repo-snapshots
          server-username: secret_BINTRAY_USERNAME
          server-password: secret_BINTRAY_PASSWORD

      # Execute the Maven deploy command to compile, package, test, verify, and publish to SNAPSHOT repository
      - name: Maven Deploy
        run: mvn -B deploy --file pom.xml
        env:
          secret_BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
          secret_BINTRAY_PASSWORD: ${{ secrets.BINTRAY_PASSWORD }}
